# -*- coding: utf-8 -*-
"""Data_Preprocessing

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SHTQAapDXhCFDHnE-_MyQ8tiyEoAbT_8
"""

def text_process(X): 
  data_list = []
  for text in X:
        text = re.sub(r'[!@#$(),n"%^*?:;~`0-9]', ' ', text)
        text = re.sub(r'[[]]', ' ', text)
        text = text.lower()
        data_list.append(text)
  return data_list

from sklearn.feature_extraction.text import CountVectorizer
def bag_of_words: 
  cv = CountVectorizer()
  X = cv.fit_transform(data_list).toarray()
  return X